### ISSUE TITLE
question about alphas

### ISSUE THREAD

**Issue by Chao86** [motokimura/octconv_pytorch#1]
if alphas=(0.0,0.5),
then self.ch_in_lf = int(alpha_in * in_channels)=0, self.ch_in_hf = in_channels,
self.ch_out_lf = int(0.5 * out_channels),self.ch_out_hf = out_channels - self.ch_out_lf;
" if not (self.ch_out_hf == 0 or self.ch_in_hf == 0):"and "if not (self.ch_out_lf == 0 or self.ch_in_hf == 0):"will be  executed simultaneously?

**Comment by Chao86** [comment]
> if alphas=(0.0,0.5),
> then self.ch_in_lf = int(alpha_in * in_channels)=0, self.ch_in_hf = in_channels,
> self.ch_out_lf = int(0.5 * out_channels),self.ch_out_hf = out_channels - self.ch_out_lf;
> " if not (self.ch_out_hf == 0 or self.ch_in_hf == 0):"and "if not (self.ch_out_lf == 0 or self.ch_in_hf == 0):"will be  executed simultaneously?

sorry, i have got it

**Comment by motokimura** [comment]
Yes! They should be.

**Comment by Chao86** [comment]
> Yes! They should be.

Thank you !
